Repository Frame-It/frame-it-front, pull requests merged in 2024-10, with the labels that each got.

#53 51 feat recruit detail
  package-lock.json
  package.json
  src/app/(project)/project-management/layout.tsx
  src/app/(project)/project-recruitment/[id]/layout.tsx
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/app/(project)/project-register/layout.tsx
  src/components/common/date-picker.tsx
  src/components/common/drawer.tsx
  src/components/project/drawer-content.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/styles/date-picker.css
  src/types/project.ts
Labels: enhancement

#57 54 feat recruit api
  src/app/(main)/recruit/page.tsx
  src/app/(my)/my-page/book-mark/page.tsx
  src/app/(project)/project-management/[id]/page.tsx
  src/app/(project)/project-management/list/page.tsx
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/app/(project)/project-register/layout.tsx
  src/app/(project)/project-register/page.tsx
  src/app/(project)/review-register/page.tsx
  src/components/common/concept-tag.tsx
  src/components/common/date-picker.tsx
  src/components/common/filter-tabs.tsx
  src/components/common/tag-list.tsx
  src/components/my-page/menu.tsx
  src/components/project/drawer-content.tsx
  src/components/project/management/applicant-list.tsx
  src/components/project/management/apply-info.tsx
  src/components/project/management/management-tabs.tsx
  src/components/project/management/progress-box.tsx
  src/components/project/management/project-progress.tsx
  src/components/project/partner-item.tsx
  src/components/project/project-info.tsx
  src/components/project/project-list-item.tsx
  src/components/project/project-list.tsx
  src/components/project/recruit-card.tsx
  src/components/project/recruitment/drawer-content.tsx
  src/components/project/recruitment/dropdown-button.tsx
  src/components/project/recruitment/filter-drawers.tsx
  src/components/project/recruitment/recruit-client.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/write/complete.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/constants/icons/project-icon.tsx
  src/constants/project.ts
  src/lib/api/project.ts
  src/store/project-regist-store.tsx
  src/store/recruit-store.tsx
  src/types/filter.ts
  src/types/project.ts
  src/types/project.type.ts
Labels: enhancement

#63 58 feat manage api
  public/icon/sqaure-uncheck-icon.svg
  public/icon/square-check-icon.svg
  src/app/(auth)/login/page.tsx
  src/app/(main)/recruit/page.tsx
  src/app/(project)/project-management/[id]/page.tsx
  src/app/(project)/project-management/cancel-register/[id]/page.tsx
  src/app/(project)/project-management/layout.tsx
  src/app/(project)/project-management/list/page.tsx
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/app/(project)/review-register/[id]/page.tsx
  src/components/common/back-button.tsx
  src/components/common/tag-list.tsx
  src/components/project/apply-member-item.tsx
  src/components/project/cancel/cancel-register.tsx
  src/components/project/management/applicant-list.tsx
  src/components/project/management/apply-info.tsx
  src/components/project/management/guest-completed.tsx
  src/components/project/management/guest-in-progress.tsx
  src/components/project/management/host-in-progress.tsx
  src/components/project/management/host-info.tsx
  src/components/project/management/management-guest.tsx
  src/components/project/management/management-host.tsx
  src/components/project/partner-item.tsx
  src/components/project/project-info.tsx
  src/components/project/project-list-item.tsx
  src/components/project/project-list.tsx
  src/components/project/recruit-card.tsx
  src/components/project/recruitment/drawer-content.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/review/review-dialog-button.tsx
  src/components/project/review/review-dialog.tsx
  src/components/project/review/review-register.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/components/ui/checkbox.tsx
  src/constants/guide.ts
  src/constants/icons/common-icon.tsx
  src/constants/project.ts
  src/hooks/useDisclosure.ts
  src/lib/api/project/header.ts
  src/lib/api/project/project-management.ts
  src/lib/api/project/project-recruitment.ts
  src/lib/api/project/project-review.ts
  src/types/project.type.ts
Labels: enhancement

#65 64 feat filter api
  src/app/(main)/recruit/page.tsx
  src/app/(project)/project-edit/[id]/layout.tsx
  src/app/(project)/project-edit/[id]/page.tsx
  src/app/(project)/project-management/list/page.tsx
  src/components/common/back-button.tsx
  src/components/project/management/management-tabs.tsx
  src/components/project/project-list.tsx
  src/components/project/recruitment/drawer-content.tsx
  src/components/project/recruitment/dropdown-button.tsx
  src/components/project/recruitment/filter-drawers.tsx
  src/components/project/recruitment/recruit-client.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/lib/api/project/project-management.ts
  src/lib/api/project/project-recruitment.ts
  src/store/project-regist-store.tsx
Labels: enhancement

#69 68 feat routing dm
  src/components/common/bottom-button.tsx
  src/components/common/dm-button.tsx
  src/components/project/apply-member-item.tsx
  src/components/project/management/management-guest.tsx
  src/components/project/review/review-dialog-button.tsx
  src/lib/api/chat/chat.ts
  src/lib/api/header.ts
  src/lib/api/project.ts
  src/lib/api/project/project-management.ts
  src/lib/api/project/project-recruitment.ts
  src/lib/api/project/project-review.ts
Labels: enhancement

#73 71 fix recruitment qa
  public/workbox-f1770938.js
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/components/common/drawer.tsx
  src/components/common/icon-button.tsx
  src/components/my-page/menu.tsx
  src/components/project/recruitment/drawer-content.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/constants/icons/mypage-icon.tsx
  src/middleware.ts
  src/store/project-regist-store.tsx
Labels: bug

#79 74 fix project management
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/register/layout.tsx
  src/app/(main)/layout.tsx
  src/app/(project)/project-edit/[id]/layout.tsx
  src/app/(project)/project-management/layout.tsx
  src/app/(project)/project-recruitment/[id]/layout.tsx
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/app/(project)/project-register/layout.tsx
  src/app/(project)/project-register/page.tsx
  src/app/(project)/review-register/layout.tsx
  src/components/common/tag-list.tsx
  src/components/my-studio/project-list.tsx
  src/components/project/apply-member-item.tsx
  src/components/project/management/guest-completed.tsx
  src/components/project/management/host-in-progress.tsx
  src/components/project/project-list-item.tsx
  src/components/project/recruitment/drawer-content.tsx
  src/components/project/recruitment/recruit-client.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/write/complete.tsx
  src/components/project/write/step-two.tsx
  src/lib/api/project/project-management.ts
  tailwind.config.ts
Labels: bug

#82 fix: 프로젝트 공고 수정 상세 시간 제거
  public/workbox-f1770938.js
  src/app/(project)/project-edit/[id]/page.tsx
Labels: bug

#88 80 fix recruit sync
  public/workbox-f1770938.js
  src/app/(main)/recruit/page.tsx
  src/app/(project)/project-management/list/page.tsx
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/components/project/project-list-item.tsx
  src/components/project/project-list.tsx
  src/components/project/recruit-card.tsx
  src/components/project/recruitment/filter-drawers.tsx
  src/components/project/recruitment/host-info.tsx
  src/components/project/recruitment/recruit-client.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/review/review-register.tsx
  src/components/project/write/complete.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/constants/query-keys/project.ts
  src/hooks/queries/projects/useRecruitmentMutation.ts
  src/hooks/queries/projects/useRecruitmentQuery.ts
  src/hooks/queries/projects/useRecruitmentsQuery.ts
  src/hooks/queries/projects/useToggleRecruitBookmark.ts
  src/lib/api/project/decoder.ts
  src/lib/api/project/project-management.ts
  src/lib/api/project/project.interface.ts
  src/service/project/recruitment.ts
  src/store/project-regist-store.tsx
  src/types/project.type.ts
Labels: bug, enhancement

#91 85 feat recruit address
  .eslintrc.json
  next.config.mjs
  src/app/(main)/recruit/page.tsx
  src/app/(my)/my-page/book-mark/page.tsx
  src/app/(project)/project-edit/[id]/page.tsx
  src/app/(project)/project-management/cancel-register/[id]/page.tsx
  src/app/(project)/project-recruitment/[id]/page.tsx
  src/app/(project)/review-register/[id]/page.tsx
  src/app/globals.css
  src/components/common/highlighted-text.tsx
  src/components/my-page/bookmark/bookmark-card.tsx
  src/components/project/apply-member-item.tsx
  src/components/project/cancel/cancel-register.tsx
  src/components/project/management/apply-info.tsx
  src/components/project/management/guest-completed.tsx
  src/components/project/management/guest-in-progress.tsx
  src/components/project/management/host-in-progress.tsx
  src/components/project/management/host-info.tsx
  src/components/project/management/management-guest.tsx
  src/components/project/management/management-host.tsx
  src/components/project/project-info.tsx
  src/components/project/project-list-item.tsx
  src/components/project/recruit-card.tsx
  src/components/project/recruitment/drawer-content.tsx
  src/components/project/recruitment/recruitment-bottom.tsx
  src/components/project/review/review-dialog.tsx
  src/components/project/review/review-register.tsx
  src/components/project/write/step-one.tsx
  src/components/project/write/step-two.tsx
  src/lib/api/project/decoder.ts
  src/lib/api/project/project-management.ts
  src/lib/api/project/project-recruitment.ts
  src/lib/api/project/project.interface.ts
  src/lib/schema/project-regist-schema.ts
  src/service/project/management.ts
  src/service/project/recruitment.ts
  src/service/project/review.ts
  src/service/project/vworld.ts
  src/store/project-regist-store.tsx
  src/types/project.type.ts
Labels: enhancement

#94 chore: ga 적용
  src/app/layout.tsx
  src/lib/google-analytics.tsx
Labels: enhancement

#97 fix: 삭제했던 파일 다시 삭제
  src/components/project/recruitment/recruit-client.tsx
Labels: bug

#101 Develop
  src/app/(main)/recruit/page.tsx
  src/app/layout.tsx
Labels: bug
